### ISSUE TITLE
cannot import name 'write_config' from 'utils'

### ISSUE THREAD

**Issue by luoguohui99** [Frica01/WeChatMassTool#3]
启动后报错
Virtual Environment Activated.
Traceback (most recent call last):
  File "E:\微信群发工具\WeChatMassTool-master\main.py", line 15, in <module>
    from controllers import ControllerMain
  File "E:\微信群发工具\WeChatMassTool-master\controllers\__init__.py", line 7, in <module>
    from controllers.controller_main import ControllerMain
  File "E:\微信群发工具\WeChatMassTool-master\controllers\controller_main.py", line 12, in <module>
    from utils import (read_file, write_config)
ImportError: cannot import name 'write_config' from 'utils'

**Comment by Frica01** [comment]
修好了
